/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mario_peric_utils_Encryption */

#ifndef _Included_mario_peric_utils_Encryption
#define _Included_mario_peric_utils_Encryption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mario_peric_utils_Encryption
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mario_peric_utils_Encryption_encrypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     mario_peric_utils_Encryption
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mario_peric_utils_Encryption_decrypt
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
